version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    container_name: mtt-app-dev
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    ports:
      - '8080:8080'
      - '9229:9229'
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint:
      [
        'sh',
        '-c',
        'chmod +x ./docker/dev/entrypoint && ./docker/dev/entrypoint',
      ]

  postgres:
    image: postgres:13
    container_name: mtt-postgres-dev
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'app'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: mtt-redis-dev
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  postgres_data:
  redis_data:
